version: "3.8"

services:
  tomcat:
    build: .
    container_name: tomcat-devsecops
    expose:
      - "8080"
    networks:
      - devsecops-net

  nginx:
    image: nginx:alpine
    container_name: nginx-devsecops
    depends_on:
      - tomcat
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8881:8080"
      - "9090:9090"
    networks:
      - devsecops-net

networks:
  devsecops-net:
    driver: bridge
