version: '3.8'

services:
  tomcat:
    image: uwinchester/pfa_app  
    container_name: tomcat-devsecops
    ports:
      - "8080"  
    networks:
      - devsecops-net

  nginx:
    image: owasp/modsecurity-crs:nginx-alpine  
    container_name: nginx-devsecops
    depends_on:
      - tomcat
    volumes:
      - ./nginx-modsec.conf:/etc/nginx/nginx.conf          
      - ./modsecurity.conf:/etc/nginx/modsecurity.conf  
    ports:
      - "80:80"
    networks:
      - devsecops-net

networks:
  devsecops-net:
    driver: bridge