services:
  tomcat:
    image: uwinchester/pfa_app  
    container_name: tomcat-devsecops
    ports:
      - "8080"  
    networks:
      - devsecops-net

  nginx:
    image: nginx:alpine
    container_name: nginx-devsecops
    depends_on:
      - tomcat
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"  
    networks:
      - devsecops-net

networks:
  devsecops-net:
    driver: bridge